### ISSUE TITLE
images do not match

### ISSUE THREAD

**Issue by vananasun** [DiceOwl/StableDiffusionStuff#5]
```
Error completing request                                                         | 8/28800.0 [00:02<2:41:45,  2.97it/s]
Arguments: (0, 'scary, evil, faces, eyes, surreal, dark, bright, houses, trees, sky, moon, by Algernon Blackwood, by Frans Masereel, black and white, contrasted, (((ink drawing))), moonlight, fog, mist, mountains', '((completely black)), ((completely white))', 'None', 'None', <PIL.Image.Image image mode=RGBA size=799x607 at 0x1A40605CC10>, None, None, None, None, 0, 20, 12, 4, 0, 1, False, False, 1, 1, 11.5, 0.36, -1.0, -1.0, 0, 0, 0, False, 480, 640, 0, 0, 32, 0, '', '', 6, 4.0, 1, 1, 0, 0, 0.0, 4.0, 0.1, 0.1, 1, True, False, False, 0, False, '', 1, False, 0, 1, False, False, '', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, None, '', 0.2, 0.1, 1, 1, False, True, True, False, False, False, False, 4, 1, 3600.0, 0.3, True, 1, 0, 7, False, False, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "C:\apps\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\apps\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\apps\stable-diffusion-webui\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\apps\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "C:\apps\stable-diffusion-webui\scripts\loopback_superimpose.py", line 132, in run
    init_img = Image.blend(processed.images[0], base_img, 1-superimpose)
  File "C:\apps\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3325, in blend
    return im1._new(core.blend(im1.im, im2.im, alpha))
ValueError: images do not match
```

keep in mind I added some (commented out) stuff so the exact line number is not correct

**Comment by jimlin1668478052** [comment]
Yep, I found the same problem. It works well yesterday.

**Comment by richard-schwab** [comment]
Same. I made sure the images were the same size (640x640) and still got this error.

**Comment by DiceOwl** [comment]
Yeah, there is a bug somewhere which I can't find. Try Interpolate in Latent, that does the blending a different way, which seems to be unaffected.

**Comment by DiceOwl** [comment]
I think I fixed the bug.
